# version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tanaka
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MinaRiri5105
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8082:8081"
    depends_on:
      - db
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:MinaRiri5105@db:5432/postgres?sslmode=disable

  app:
    build: .
    container_name: diary-go-app
    ports:
      - "8083:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:  
      - .env   
  

volumes:
  postgres-data:
